---
title: "Lab 7 Assignment: Group 05"
subtitle: 'Students: s243284, s242872,	s243302,	s243547,	s243360'
format:
  html:
    embed-resources: true
editor: visual
---

# Lab 07 Group Assignment

Miguel Blanco Chillerón, s243284

Daniel Gil Conejo, 242872

Luis Martín del Cerro, s243302

Natalia Feced Garcia, s243547

Xavier Chapatte Banaset, s243360

## Load Libraries

```{r}
library(tidyverse)
library(broom)
library(cowplot)
```

## Data

```{r}
target_url <- "https://github.com/ramhiser/datamicroarray/raw/master/data/gravier.RData"
output_file <- "data/gravier.RData"
curl::curl_download(url = target_url, destfile = output_file)
```

```{r}
load(file = "data/gravier.RData")
cancer_data <- gravier |> 
  bind_cols() |> 
  as_tibble()
```

## Miguel (Until first graph)

Select numeric data and run PCA

```{r}
pca_fit <- cancer_data |> 
  select(where(is.numeric)) |> 
  prcomp(scale = TRUE)
```

```{r}
pca_fit <- cancer_data |> 
  select(where(is.numeric)) |> 
  prcomp(scale = TRUE)

pca_fit |>
  augment(cancer_data) |> # add original dataset back in
  ggplot(aes(.fittedPC1, .fittedPC2, colour =)) + 
  geom_point(size = 1.5) +
  scale_color_manual(
    values = c(malignant = "#D55E00", benign = "#0072B2")
  ) +
  theme_half_open(12) + background_grid()
```

## Xavi

## Natalia

## Dani

```{r}
set.seed(676571)
cancer_data=mutate(as_tibble(pluck(gravier,"x")),y=pluck(gravier,"y"),pt_id=1:length(pluck(gravier, "y")),age=round(rnorm(length(pluck(gravier,"y")),mean=55,sd=10),1))
cancer_data=rename(cancer_data,event_label=y)
cancer_data$age_group=cut(cancer_data$age,breaks=seq(10,100,by=10))
cancer_data=relocate(cancer_data,c(pt_id,age,age_group,pt_id,event_label))

pca_fit <- cancer_data |> 
  select(where(is.numeric)) |> 
  prcomp(scale = TRUE)

pca_fit |>
  augment(cancer_data) |> # add original dataset back in
  ggplot(aes(.fittedPC1, .fittedPC2, color = event_label)) + 
  geom_point(size = 1.5) +
  scale_color_manual(
    values = c(good = "#D55E00", poor = "#0072B2")
  ) +
  theme_half_open(12) + background_grid()
```

## Luis

```{r}
pca_fit %>%
  tidy(matrix = "eigenvalues") %>%
  ggplot(aes(PC, percent)) +
  geom_col(fill = "#56B4E9", alpha = 0.8) +
  scale_x_continuous(breaks = 1:9) +
  scale_y_continuous(
    labels = scales::percent_format(),
    expand = expansion(mult = c(0, 0.01))
  ) +
  scale_x_continuous(limits = c(0, 30)) +
  theme_minimal_hgrid(12)
```
